2025-10-15 22:08:09.134130: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-10-15 22:08:16.726898: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
Picked up JAVA_TOOL_OPTIONS: -Djava.awt.headless=true -Xmx4g
Oct 15, 2025 10:08:21 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Traceback (most recent call last):
  File "NetLogoLink.java", line 132, in netLogoLink.NetLogoLink.loadModel
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home-mscluster/travhengani/miniconda3/lib/python3.13/site-packages/pynetlogo/core.py", line 246, in load_model
    self.link.loadModel(path)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
java.lang.java.lang.IllegalStateException: java.lang.IllegalStateException: unknown NetLogo version: NetLogo 6.4.0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home-mscluster/travhengani/Strict-vs.-Lenient-Tax-Enforcement-in-Sugarscape/dqn.py", line 471, in __init__
    self.netlogo.load_model(model_file)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home-mscluster/travhengani/miniconda3/lib/python3.13/site-packages/pynetlogo/core.py", line 249, in load_model
    raise NetLogoException(str(ex))
pynetlogo.core.NetLogoException: java.lang.IllegalStateException: unknown NetLogo version: NetLogo 6.4.0
Traceback (most recent call last):
  File "NetLogoLink.java", line 132, in netLogoLink.NetLogoLink.loadModel
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home-mscluster/travhengani/miniconda3/lib/python3.13/site-packages/pynetlogo/core.py", line 246, in load_model
    self.link.loadModel(path)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
java.lang.java.lang.IllegalStateException: java.lang.IllegalStateException: unknown NetLogo version: NetLogo 6.4.0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home-mscluster/travhengani/Strict-vs.-Lenient-Tax-Enforcement-in-Sugarscape/dqn.py", line 1072, in main
    sim = DQNTaxSimulation(netlogo_path, gui=USE_GUI)
  File "/home-mscluster/travhengani/Strict-vs.-Lenient-Tax-Enforcement-in-Sugarscape/dqn.py", line 471, in __init__
    self.netlogo.load_model(model_file)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home-mscluster/travhengani/miniconda3/lib/python3.13/site-packages/pynetlogo/core.py", line 249, in load_model
    raise NetLogoException(str(ex))
pynetlogo.core.NetLogoException: java.lang.IllegalStateException: unknown NetLogo version: NetLogo 6.4.0
slurmstepd-mscluster16: error: *** JOB 163379 ON mscluster16 CANCELLED AT 2025-10-15T23:32:30 ***
